[package]
name = "redis-driver"
version = "0.1.0"
keywords = ["redis", "database"]
categories = ["database", "asynchronous"]
description = "Redis async driver for Rust"
homepage = "https://github.com/dahomey-technologies/redis-driver-rs"
repository = "https://github.com/dahomey-technologies/redis-driver-rs"
documentation = "https://docs.rs/redis-driver"
readme = "README.md"
license-file = "LICENSE"
edition = "2021"

[features]
default = ["tokio-runtime"]
tokio-runtime = [
    "tokio/macros",
    "tokio/net",
    "tokio/rt",
    "tokio/io-util",
]
tokio-tls = [
    "tokio-native-tls",
    "tls"
]
async-std-runtime = [
    "async-std",
    "async-std/attributes",
    "tokio-util/compat",
    "async-native-tls",
]
async-std-tls = [
    "async-native-tls",
    "tls"
]
pool = ["bb8"]
tls = ["native-tls"]

[dependencies]
async-std = { version = "1", features = ["attributes"], optional = true }
futures = "0"
bytes = "1"
tokio = { version = "1", features = ["time", "io-util"] }
tokio-util = { version = "0", features = ["codec"] }
itoa = "1"
dtoa = "1"
smallvec = { version = "1", features = ["union"] }
bb8 = { version = "0", optional = true }
url = "2"
native-tls = { version = "0", optional = true }
tokio-native-tls = { version = "0", optional = true }
async-native-tls = { version = "0", optional = true }
log = "0"
crc16 = "0"
rand = "0.8.4"

[dev-dependencies]
serial_test = "0"
tokio = { version = "1", features = ["rt-multi-thread"] }
rand = "0.8.4"
env_logger = "0"
