[package]
name = "rustis"
version = "0.1.0"
keywords = ["redis", "database", "async", "cluster", "sentinel"]
categories = ["database", "asynchronous"]
description = "Redis async driver for Rust"
homepage = "https://github.com/dahomey-technologies/rustis"
repository = "https://github.com/dahomey-technologies/rustis"
documentation = "https://docs.rs/rustis"
readme = "README.md"
license-file = "LICENSE"
edition = "2021"

[features]
default = ["tokio-runtime"]
tokio-runtime = [
    "tokio/macros",
    "tokio/net",
    "tokio/rt",
    "tokio/io-util",
]
tokio-tls = [
    "tokio-native-tls",
    "tls"
]
async-std-runtime = [
    "async-std",
    "async-std/attributes",
    "tokio-util/compat",
    "async-native-tls",
]
async-std-tls = [
    "async-native-tls",
    "tls"
]
pool = ["bb8"]
tls = ["native-tls"]
redis-json = []
redis-search = []
redis-graph = []
redis-bloom = []
redis-time-series = []
redis-stack = [
    "redis-json",
    "redis-search",
    "redis-graph",
    "redis-bloom",
    "redis-time-series"
]

[dependencies]
async-std = { version = "1.12", features = ["attributes"], optional = true }
futures = "0.3"
bytes = "1.3"
tokio = { version = "1.23", features = ["time", "io-util", "sync"] }
tokio-util = { version = "0.7", features = ["codec"] }
itoa = "1.0"
dtoa = "1.0"
smallvec = { version = "1.10", features = ["union", "serde"] }
bb8 = { version = "0.8", optional = true }
url = "2.3"
native-tls = { version = "0.2", optional = true }
tokio-native-tls = { version = "0.3", optional = true }
async-native-tls = { version = "0.4", optional = true }
log = "0.4"
crc16 = "0.4"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
socket2 = "0.4"
memchr = "2.5"

[dev-dependencies]
serial_test = "0.10"
tokio = { version = "1.23", features = ["rt-multi-thread"] }
rand = "0.8"
env_logger = "0.10"
smallvec = { version = "1.10", features = ["serde"] }
criterion = "0.4"
redis = { version = "0.22", features = ["aio", "tokio-comp"] }
fred = "6.0.0-beta.2"

[package.metadata.docs.rs]
features = ["tokio-runtime", "tokio-tls", "redis-stack", "pool"]
rustdoc-args = ["--cfg", "docsrs"]

[[bench]]
name = "generic_api"
harness = false

[[bench]]
name = "native_api"
harness = false

[[bench]]
name = "pipeline"
harness = false

[[bench]]
name = "multiplexer"
harness = false
