name: Build and Test

on:
  push:
    paths:
      - "src/**"
      - "redis/**"
      - ".github/workflows/**"
      - "Cargo.toml"
    branches:
      - "**"
    tags-ignore:
      - "*.*.*"
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "Cargo.toml"
    branches:
      - "**"
    tags-ignore:
      - "*.*.*"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run cargo check
        run: cargo check

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Create Redis containers
        run: |
          cd /home/runner/work/rustis/rustis/redis/
          sh ./docker_up.sh
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features pool,tokio-tls,redis-stack
